# Generated by Django 4.1.4 on 2022-12-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customername', models.CharField(max_length=20)),
                ('Customerid', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=20)),
                ('PanCard', models.CharField(max_length=20)),
                ('AadharcardNo', models.CharField(max_length=20)),
                ('PhoneNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Staffname', models.CharField(max_length=20)),
                ('Staffid', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=20)),
                ('PanCard', models.CharField(max_length=20)),
                ('AadharcardNo', models.CharField(max_length=20)),
                ('PhoneNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VehicleType', models.CharField(max_length=20)),
                ('VehicleNo', models.IntegerField(primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('Stock', models.IntegerField()),
                ('Stockid', models.IntegerField(primary_key=True, serialize=False)),
                ('VehicleNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingbystaff',
            fields=[
                ('Bookingid', models.IntegerField(primary_key=True, serialize=False)),
                ('Staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.staff')),
                ('Stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingbycustomer',
            fields=[
                ('custid', models.IntegerField(primary_key=True, serialize=False)),
                ('Staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.staff')),
                ('Stockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.stock')),
            ],
        ),
    ]
