# Generated by Django 4.1.4 on 2023-01-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='AadharcardNo',
            new_name='CustomerAadharcardNo',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='CustomerAddress',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customerid',
            new_name='CustomerID',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customername',
            new_name='CustomerName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PanCard',
            new_name='CustomerPanCard',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PhoneNo',
            new_name='CustomerPhoneNo',
        ),
    ]
